services:
  - type: web
    name: music-web-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://my-music-bice.vercel.app
      - key: SERVER_URL
        value: https://music-web-sqpk.onrender.com
